name: xsoulspace
description: A small home for soulful ideas.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Commands:
# pub outdated --mode=null-safety
# flutter run --no-sound-null-safety
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+1

environment:
  # https://dart.dev/get-dart#release-channels
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  badges: ^2.0.2
  blur: ^3.1.0
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  flutter_svg: ^1.0.3
  json_annotation: ^4.4.0
  path_to_regexp: ^0.4.0
  provider: ^6.0.2
  quiver: ^3.1.0
  sliver_tools: ^0.2.6
  url_launcher: ^6.1.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.10
  flutter_gen: ^4.1.6
  flutter_gen_runner: ^4.1.6
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  dart_code_metrics: ^4.15.0

# For information see the following page:
# https://pub.dev/packages/flutter_gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  # line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icons/github/
    - assets/sections/
    - assets/json/
    - assets/badges/

  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: google_fonts/NotoColorEmoji.ttf
    - family: NotoSans
      fonts:
        - asset: google_fonts/NotoSans-Regular.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
