name: app_design_core
description: design ui kit
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  animate_do: ^3.1.2
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_portal: ^1.1.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  google_fonts: ^6.1.0
  life_hooks: ^0.0.19
  pointer_interceptor: ^0.9.3+7
  sliver_tools: ^0.2.12
  tap_builder: ^0.5.0
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  webview_flutter_web: ^0.2.2+3

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  xsoulspace_lints: ^0.0.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
# assets:
#   - assets/images/
# To add assets to your application, add an assets section, like this:
# assets:
#   - google_fonts/
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# fonts:
#   - family: la_icons
#     fonts:
#       - asset: packages/la_design_core/fonts/la_icons.ttf
