name: app_core
description: core to use inside app
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.13.3
  cloud_firestore_platform_interface: ^6.0.7
  cloud_firestore_web: ^3.8.7
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  equatable: ^2.0.5
  firebase_analytics: ^10.7.2
  firebase_analytics_web: ^0.5.5+9
  firebase_auth: ^4.15.0
  firebase_auth_platform_interface: ^7.0.6
  firebase_auth_web: ^5.8.9
  firebase_core: ^2.24.0
  firebase_core_web: ^2.9.0
  firebase_crashlytics: ^3.4.6
  firebase_dynamic_links: ^5.4.6
  firebase_ui_auth: ^1.11.0
  firebase_ui_firestore: ^1.5.15
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  flutter_keyboard_visibility: ^5.4.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  life_hooks: ^0.0.19
  logger: ^2.0.2+1
  path_to_regexp: ^0.4.0
  provider: ^6.1.1
  quiver: ^3.2.1
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  app_design_core:
    path: ../app_design_core
  universal_io: ^2.2.2
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  xsoulspace_lints: ^0.0.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
# assets:
#   - assets/images/
# fonts:
#   - family: asgard_icons
#     fonts:
#       - asset: packages/la_design_core/fonts/asgard_icons.ttf
#   - family: Poppins
#     fonts:
#       - asset: packages/la_design_core/fonts/Poppins-Regular.ttf
#         weight: 400
#       - asset: packages/la_design_core/fonts/Poppins-Bold.ttf
#         weight: 700
flutter_intl:
  enabled: true
